unit Udm;

interface

uses
  System.SysUtils, System.Classes, FireDAC.Stan.Intf, FireDAC.Stan.Option,
  FireDAC.Stan.Error, FireDAC.UI.Intf, FireDAC.Phys.Intf, FireDAC.Stan.Def,
  FireDAC.Stan.Pool, FireDAC.Stan.Async, FireDAC.Phys, FireDAC.VCLUI.Wait,
  FireDAC.Stan.Param, FireDAC.DatS, FireDAC.DApt.Intf, FireDAC.DApt, Data.DB,
  FireDAC.Comp.DataSet, FireDAC.Comp.Client, FireDAC.Phys.FB, FireDAC.Phys.FBDef,
  Vcl.Dialogs,inifiles,Vcl.Forms, Datasnap.DBClient, Datasnap.Provider,
  FireDAC.Phys.IBBase, FireDAC.Comp.UI;

type
  TDM = class(TDataModule)
    FDConn: TFDConnection;
    SqlProdutos: TFDQuery;
    SqlFiliais: TFDQuery;
    sqlClientes: TFDQuery;
    Query: TFDQuery;
    FDConstrole: TFDQuery;
    dspControle: TDataSetProvider;
    cdsControle: TClientDataSet;
    cdsControleCAMPO: TStringField;
    cdsControleVALOR: TFloatField;
    FDGUIxWaitCursor1: TFDGUIxWaitCursor;
    FDPhysFBDriverLink1: TFDPhysFBDriverLink;
    FDCeCadFin: TFDQuery;
    dspCeCadFin: TDataSetProvider;
    cdsCeCadFin: TClientDataSet;
    FDCeLotes: TFDQuery;
    FdqNumeroLancamentosLoja: TFDQuery;
    dspNUmeroLancamentosLoja: TDataSetProvider;
    cdsNumeroLancamentosLoja: TClientDataSet;
    cdsNumeroLancamentosLojaCOUNT: TIntegerField;
    cdsCdLancamento: TClientDataSet;
    FdLancamentosLoja: TFDQuery;
    dspLancamentosLoja: TDataSetProvider;
    cdsLancamentosLoja: TClientDataSet;
    cdsLancamentosLojaCD_LANCAMENTO: TFloatField;
    dspCeLotes: TDataSetProvider;
    cdsCelotes: TClientDataSet;
    cdsCelotesID_PRODUTO: TFloatField;
    cdsCelotesCD_FILIAL: TFloatField;
    cdsCelotesCD_PRODUTO: TStringField;
    cdsCelotesDESCRICAO: TStringField;
    cdsCelotesCD_LABORATORIO: TFloatField;
    cdsCelotesCD_GRUPO: TFloatField;
    cdsCelotesCD_CONVENIO: TFloatField;
    cdsCelotesCD_CLIENTE: TFloatField;
    cdsCelotesCD_VENDEDOR: TFloatField;
    cdsCelotesCD_OPERADOR: TFloatField;
    cdsCelotesCD_USUARIO: TFloatField;
    cdsCelotesCD_FORMA_PAGAMENTO: TFloatField;
    cdsCelotesCD_VENDA: TFloatField;
    cdsCelotesCUSTO_MEDIO: TFMTBCDField;
    cdsCelotesCUSTO_UNITARIO: TFMTBCDField;
    cdsCelotesDATA_LANCAMENTO: TDateField;
    cdsCelotesDATA_CAIXA: TDateField;
    cdsCelotesQUANTIDADE: TFloatField;
    cdsCelotesVALOR: TFMTBCDField;
    cdsCelotesNOTA_FISCAL: TStringField;
    cdsCelotesDESCONTO: TFMTBCDField;
    cdsCelotesPROMOCAO: TFMTBCDField;
    cdsCelotesTIPO_VENDA: TStringField;
    cdsCelotesTIPO_PAGAMENTO: TStringField;
    cdsCelotesENTRADA_SAIDA: TStringField;
    cdsCelotesETIQUETA: TStringField;
    cdsCelotesENTREGA: TStringField;
    cdsCelotesHORA: TTimeField;
    cdsCelotesESTOQUE_POSVENDA: TFloatField;
    cdsCelotesTROCA: TStringField;
    cdsCelotesENVIADO: TStringField;
    cdsCelotesNUMERO: TFloatField;
    cdsCelotesTERMINAL: TFloatField;
    cdsCelotesUSUARIO: TStringField;
    cdsCelotesCD_LANCAMENTO: TFloatField;
    cdsCelotesCOMISSAO: TFMTBCDField;
    cdsCelotesARREDONDAMENTO: TFMTBCDField;
    cdsCelotesCD_CLASSE: TFloatField;
    cdsCelotesID_OPERADORCAIXA: TFloatField;
    cdsCelotesOBSERVACAO: TStringField;
    cdsCelotesTRN: TStringField;
    cdsCelotesTRANSACAOTRN: TStringField;
    cdsCelotesLOTETRN: TStringField;
    cdsCelotesAUTORIZACAOTRN: TStringField;
    cdsCelotesSUBSIDIOTRN: TFloatField;
    cdsCelotesNOTAMANUAL: TStringField;
    cdsCelotesCD_FILIAL_ORIGEM: TFloatField;
    cdsCelotesID_PRODUTO_LOTE: TFloatField;
    cdsCelotesNCM: TStringField;
    cdsCelotesCFOP: TStringField;
    cdsCelotesCST: TStringField;
    cdsCelotesICMS: TStringField;
    cdsCelotesCODIGO_BARRAS: TStringField;
    cdsCelotesECF: TStringField;
    cdsCelotesCD_SUBGRUPO: TFloatField;
    cdsCelotesSERIE_NOTA_FISCAL: TStringField;
    cdsCelotesID_CLIENTE_PROPRIEDADE: TFloatField;
    cdsCelotesCEST: TStringField;
    cdsCelotesFCP: TFMTBCDField;
    cdsCelotesPERCENTUALREDUCAO: TFMTBCDField;
    cdsCelotesCOMPOSTO: TStringField;
    cdsCelotesID_PRODUTO_PRINCIPAL: TFloatField;
    cdsCelotesVENDA_FIDELIDADE: TStringField;
    cdsCelotesVENDA_QUANTIDADE: TStringField;
    cdsCelotesIFOOD: TStringField;
    cdsCelotesFARMACIASAPP: TStringField;
    FdParametros: TFDQuery;
    dpParametros: TDataSetProvider;
    cdsParametros: TClientDataSet;
    cdsParametrosCD_FILIAL: TFloatField;
    cdsParametrosTIPO_LOJA: TStringField;
    cdsParametrosCODIGOUSUARIO: TStringField;
    cdsParametrosNOMEFANTASIA: TStringField;
    cdsParametrosRAZAO: TStringField;
    cdsParametrosENDERECO: TStringField;
    cdsParametrosBAIRRO: TStringField;
    cdsParametrosCIDADE: TStringField;
    cdsParametrosUF: TStringField;
    cdsParametrosCEP: TStringField;
    cdsParametrosCX_POSTAL: TStringField;
    cdsParametrosCGC: TStringField;
    cdsParametrosINSCRICAO: TStringField;
    cdsParametrosFONE: TStringField;
    cdsParametrosFAX: TStringField;
    cdsParametrosINSC_MUNIC: TStringField;
    cdsParametrosURL1: TStringField;
    cdsParametrosURL2: TStringField;
    cdsParametrosURL3: TStringField;
    cdsParametrosURL4: TStringField;
    cdsParametrosURL5: TStringField;
    cdsParametrosMENS_PROM2: TStringField;
    cdsParametrosMENS_PROM3: TStringField;
    cdsParametrosMENS_PROM4: TStringField;
    cdsParametrosMENS_PROM5: TStringField;
    cdsParametrosFOTO: TStringField;
    cdsParametrosCAMINHOMATRIZ: TStringField;
    cdsParametrosCUSTO_OPERACIONAL: TFloatField;
    cdsParametrosPERCENTUAL_SIMPLES: TFloatField;
    cdsParametrosCALCULO_CUSTO: TStringField;
    cdsParametrosCHAVE: TStringField;
    cdsParametrosCONTRA_CHAVE: TStringField;
    cdsParametrosDT_IMPLANTACAO: TStringField;
    cdsParametrosDT_AUTENTICACAO: TStringField;
    cdsParametrosCD_IMPRESSORA: TFloatField;
    cdsParametrosETIQUETA_TIPO: TFloatField;
    cdsParametrosETIQUETA: TStringField;
    cdsParametrosDESCONTOMAXIMO: TFloatField;
    cdsParametrosIMPRIME_PREVENDA: TStringField;
    cdsParametrosPREVENDA: TStringField;
    cdsParametrosDESCONTOGERENTE: TFloatField;
    cdsParametrosNVIASCUPOMENTREGA: TFloatField;
    cdsParametrosTEMPODESCANSO: TFloatField;
    cdsParametrosCHAVEF10: TStringField;
    cdsParametrosRESUMOCAIXA_ITEM_1: TStringField;
    cdsParametrosRESUMOCAIXA_ITEM_2: TStringField;
    cdsParametrosRESUMOCAIXA_ITEM_3: TStringField;
    cdsParametrosRESUMOCAIXA_ITEM_4: TStringField;
    cdsParametrosRESUMOCAIXA_ITEM_5: TStringField;
    cdsParametrosRESUMOCAIXA_ITEM_6: TStringField;
    cdsParametrosRESUMOCAIXA_ITEM_7: TStringField;
    cdsParametrosRESUMOCAIXA_ITEM_8: TStringField;
    cdsParametrosRESUMOCAIXA_ITEM_9: TStringField;
    cdsParametrosRESUMOCAIXA_ITEM_10: TStringField;
    cdsParametrosRESUMOCAIXA_ITEM_11: TStringField;
    cdsParametrosRESUMOCAIXA_ITEM_12: TStringField;
    cdsParametrosIMPRIMEORCAMENTO: TStringField;
    cdsParametrosTIPODESCONTO: TStringField;
    cdsParametrosURLCOTACOES: TStringField;
    cdsParametrosSMTP: TStringField;
    cdsParametrosUSUARIO_SMTP: TStringField;
    cdsParametrosSENHA_SMTP: TStringField;
    cdsParametrosNAOFISCAL: TFloatField;
    cdsParametrosETIQUETAS_PRN: TFloatField;
    cdsParametrosVENDEESTOQUENEGATIVO: TStringField;
    cdsParametrosPEDECRMBALCAO: TStringField;
    cdsParametrosPEDECRMCHECKOUT: TStringField;
    cdsParametrosGERARCR_TRANSFER: TStringField;
    cdsParametrosGERARCP_TRANSFER: TStringField;
    cdsParametrosLIMITEDECREDITO: TFloatField;
    cdsParametrosSERVIDORMATRIZ: TStringField;
    cdsParametrosESTOQUEMINIMO: TStringField;
    cdsParametrosNVIASTRANSFERENCIA: TFloatField;
    cdsParametrosUTILIZAPERFUMISTA: TStringField;
    cdsParametrosDATAATUAL: TDateField;
    cdsParametrosABREENTREGA: TStringField;
    cdsParametrosCUPOMDETALHADOPREVENDA: TStringField;
    cdsParametrosPARCELAVENDAS: TStringField;
    cdsParametrosDESCONTOOPERADORCALLCENTER: TFloatField;
    cdsParametrosDESCONTOGERENTECALLCENTER: TFloatField;
    cdsParametrosPRECIFICACAO_UNICA: TStringField;
    cdsParametrosCOLUNASIMPRESSORANAOFISCAL: TFloatField;
    cdsParametrosMANTEMDESCRICAOPRODUTO: TStringField;
    cdsParametrosINSTRUCOESBOLETO: TStringField;
    cdsParametrosUSATEF: TStringField;
    cdsParametrosTEFTEMPOESPERA: TFloatField;
    cdsParametrosTEFTEMPOMENSAGEM: TFloatField;
    cdsParametrosCONTROLEMEDICAMENTO: TStringField;
    cdsParametrosCONSULTACHEQUE: TStringField;
    cdsParametrosIDENTIFICARCLIENTE: TStringField;
    cdsParametrosPERIODO_VENCIMENTO: TFloatField;
    cdsParametrosPERIODO_VENCIMENTO_VENDAS: TFloatField;
    cdsParametrosIDENTIFICAVENDAMANUAL: TStringField;
    cdsParametrosTRABALHARCAIXADIAANTERIOR: TStringField;
    cdsParametrosUSAPRECOCONCORRENTE: TStringField;
    cdsParametrosPRECOPROMOCAOAUTOMATICO: TStringField;
    cdsParametrosCOMPROVANTEFIADO: TStringField;
    cdsParametrosMANTEMDESCRICAOPRODUTOCOMPRA: TStringField;
    cdsParametrosFARMACEUTICONOME: TStringField;
    cdsParametrosFARMACEUTICOCPF: TStringField;
    cdsParametrosFARMACEUTICOCRF: TStringField;
    cdsParametrosFARMACEUTICOUF: TFloatField;
    cdsParametrosDATA_ULTIMA_TRANSMISSAO_SNGPC: TDateField;
    cdsParametrosALTERAMARGEMNOTA: TStringField;
    cdsParametrosSOMAIPI: TStringField;
    cdsParametrosCAMINHOAUTENTICACAO: TStringField;
    cdsParametrosPEDIRSENHAVENDEDOR: TStringField;
    cdsParametrosVENDASDINHEIRO: TStringField;
    cdsParametrosVENDASCARTAO: TStringField;
    cdsParametrosVENDASCONVENIO: TStringField;
    cdsParametrosVENDASCHEQUEPRE: TStringField;
    cdsParametrosVENDASCREDITO: TStringField;
    cdsParametrosVENDASCHEQUEAVISTA: TStringField;
    cdsParametrosOUTROSRECEBIMENTOS: TStringField;
    cdsParametrosSAIDAS: TStringField;
    cdsParametrosIMAGEM: TBlobField;
    cdsParametrosBAIXAAUTOMATICACHEQUEPRE: TStringField;
    cdsParametrosPERCENTUALPREMIACAO: TFloatField;
    cdsParametrosVALORMINIMOPREMIACAO: TFloatField;
    cdsParametrosPERCENTUALJUROSCONTASRECEBER: TFloatField;
    cdsParametrosCD_CONTA_BAIXA_CHEQUE: TFloatField;
    cdsParametrosINSTANCIAMULTIPLA: TStringField;
    cdsParametrosDESCONTOGRUPOSOBRECONVENIO: TStringField;
    cdsParametrosRESUMOCAIXA_ITEM_13: TStringField;
    cdsParametrosRESGATAPREVENDA: TStringField;
    cdsParametrosVALORALERTASANGRIA: TFloatField;
    cdsParametrosVENDEDORAUTOMATICO: TFloatField;
    cdsParametrosDISCRIMINARDESCONTOCUPOM: TStringField;
    cdsParametrosPROMOCAODESCONTOCUPOM: TStringField;
    cdsParametrosUSAGUILHOTINA: TStringField;
    cdsParametrosCONVENIOTRN: TFloatField;
    cdsParametrosCLIENTETRN: TFloatField;
    cdsParametrosVENCIMENTOTRN: TFloatField;
    cdsParametrosCONVENIOEPHARMA: TFloatField;
    cdsParametrosCLIENTEEPHARMA: TFloatField;
    cdsParametrosVENCIMENTOEPHARMA: TFloatField;
    cdsParametrosCONVENIOFUNCIONALCARD: TFloatField;
    cdsParametrosCLIENTEFUNCIONALCARD: TFloatField;
    cdsParametrosVENCIMENTOFUNCIONALCARD: TFloatField;
    cdsParametrosCONVENIOVIDALINK: TFloatField;
    cdsParametrosCLIENTEVIDALINK: TFloatField;
    cdsParametrosVENCIMENTOVIDALINK: TFloatField;
    cdsParametrosCONVENIOFARMACIAPOPULAR: TFloatField;
    cdsParametrosCLIENTEFARMACIAPOPULAR: TFloatField;
    cdsParametrosVENCIMENTOFARMACIAPOPULAR: TFloatField;
    cdsParametrosLOGINFARMACIAPOPULAR: TStringField;
    cdsParametrosSENHAFARMACIAPOPULAR: TStringField;
    cdsParametrosLOGINFIDELIZE: TStringField;
    cdsParametrosSENHAFIDELIZE: TStringField;
    cdsParametrosUSAIMS: TStringField;
    cdsParametrosCHAVESINTEGRA: TStringField;
    cdsParametrosIMPRIMIRRESUMOECF: TStringField;
    cdsParametrosIMPRIMIRVINCULADOPARAENTREGA: TStringField;
    cdsParametrosCODIGOIMS: TStringField;
    cdsParametrosVALORPONTUACAO: TFloatField;
    cdsParametrosPONTOSRESGATE: TIntegerField;
    cdsParametrosVALORRESGATE: TFloatField;
    cdsParametrosSUBSTITUTOTRIBUTARIO: TStringField;
    cdsParametrosCONTRIBUINTE_IPI: TStringField;
    cdsParametrosCOMPLEMENTO: TStringField;
    cdsParametrosNUMERO: TStringField;
    cdsParametrosCONTATO: TStringField;
    cdsParametrosPAF_LAUDO: TStringField;
    cdsParametrosPAF_CNPJ: TStringField;
    cdsParametrosPAF_IE: TStringField;
    cdsParametrosPAF_IM: TStringField;
    cdsParametrosPAF_RAZAO: TStringField;
    cdsParametrosPAF_ENDERECO: TStringField;
    cdsParametrosPAF_TELEFONE: TStringField;
    cdsParametrosPAF_CONTATO: TStringField;
    cdsParametrosPAF_NOMECOMERCIAL: TStringField;
    cdsParametrosPAF_VERSAO: TStringField;
    cdsParametrosPAF_EXECUTAVEL: TStringField;
    cdsParametrosPAF_MD5: TStringField;
    cdsParametrosPAF_ERPAFECF: TStringField;
    cdsParametrosPAF_CHAVEPUBLICA: TStringField;
    cdsParametrosPAF_CHAVEPRIVADA: TStringField;
    cdsParametrosPAF_DATA: TStringField;
    cdsParametrosEXIBECOMISSAOVENDA: TStringField;
    cdsParametrosCONTROLALOTES: TStringField;
    cdsParametrosCONCLUI_TRANSFERENCIAS: TStringField;
    cdsParametrosENVIA_TRANSFERENCIAS: TStringField;
    cdsParametrosCONFERENCIAVENDA: TStringField;
    cdsParametrosUSARVENDEDORLOJA: TStringField;
    cdsParametrosCD_VENDEDORLOJA: TFloatField;
    cdsParametrosPHARMALINKSENHA: TStringField;
    cdsParametrosPHARMALINKURL: TStringField;
    cdsParametrosPHARMALINKIP: TStringField;
    cdsParametrosDIASBLOQUEIOCLIENTE: TIntegerField;
    cdsParametrosEXIBIRVALORVENDA: TStringField;
    cdsParametrosLINHASAVANCO: TFloatField;
    cdsParametrosEXIBIRPRODUTOSRELACIONADOS: TStringField;
    cdsParametrosNOMEREDE: TStringField;
    cdsParametrosCODIGOCLOSEUP: TStringField;
    cdsParametrosRECEBIMENTOPARCIALCONTA: TStringField;
    cdsParametrosSERVIDORLOJA: TStringField;
    cdsParametrosCD_MUNICIPIO: TStringField;
    cdsParametrosPERFIL: TStringField;
    cdsParametrosEMAIL: TStringField;
    cdsParametrosCONTACUSTOVENDA: TFloatField;
    cdsParametrosVIASVINCULADOENTRGA: TIntegerField;
    cdsParametrosTEXTOPADRAOGARANTIA: TStringField;
    cdsParametrosVERSAO_GESTOR: TStringField;
    cdsParametrosVERSAO_LOJA: TStringField;
    cdsParametrosDIASSEMVENDER: TIntegerField;
    cdsParametrosRESUMOCAIXA_ITEM_14: TStringField;
    cdsParametrosNUMEROSERIECERTIFICADO: TStringField;
    cdsParametrosNFEAMBIENTE: TStringField;
    cdsParametrosNFECFOP: TFloatField;
    cdsParametrosNFECFOPTRANSFERENCIAENTRADA: TFloatField;
    cdsParametrosNFECFOPTRANSFERENCIASAIDA: TFloatField;
    cdsParametrosNFECFOPDEVOLUCAO: TFloatField;
    cdsParametrosNFECFOPENTRADA: TFloatField;
    cdsParametrosNFEULTIMANOTAEMITIDA: TStringField;
    cdsParametrosNFEULTIMOLOTEENVIADO: TStringField;
    cdsParametrosTIPO_TEF: TStringField;
    cdsParametrosCD_VENDA: TFloatField;
    cdsParametrosARMAZENAPOSICAOESTOQUEDATA: TStringField;
    cdsParametrosCONTADORNOME: TStringField;
    cdsParametrosCONTADORCPF: TStringField;
    cdsParametrosCONTADORCRC: TStringField;
    cdsParametrosCONTADORCNPJ: TStringField;
    cdsParametrosCONTADORENDERECO: TStringField;
    cdsParametrosCONTADORNUMERO: TStringField;
    cdsParametrosCONTADORCOMPLEMENTO: TStringField;
    cdsParametrosCONTADORBAIRRO: TStringField;
    cdsParametrosCONTADORCEP: TStringField;
    cdsParametrosCONTADORTELEFONE: TStringField;
    cdsParametrosCONTADORFAX: TStringField;
    cdsParametrosCONTADOREMAIL: TStringField;
    cdsParametrosCONTADORCD_MUNICIPIO: TStringField;
    cdsParametrosCHAVENFE: TStringField;
    cdsParametrosACODEURL: TStringField;
    cdsParametrosACODEUSUARIO: TStringField;
    cdsParametrosACODESENHA: TStringField;
    cdsParametrosPHARMALINKUSUARIO: TStringField;
    cdsParametrosICMSINTERESTADUALSIMPLES: TFMTBCDField;
    cdsParametrosICMSINTERESTADUALREDUZIDO: TFMTBCDField;
    cdsParametrosSERIENOTANFE: TStringField;
    cdsParametrosCD_PAIS: TStringField;
    cdsParametrosSERVIDORCALLCENTER: TStringField;
    cdsParametrosPREENCHERRECEITACONTROLADO: TStringField;
    cdsParametrosSMSTECNICO: TStringField;
    cdsParametrosSMSGERENCIAL: TStringField;
    cdsParametrosUSATECBAN: TStringField;
    cdsParametrosUSAHIPERCARD: TStringField;
    cdsParametrosUSAREDECARDAMEXVISA: TStringField;
    cdsParametrosABREFINALIZACAOBALCAO: TStringField;
    cdsParametrosEXIBECUSTOBALCAO: TStringField;
    cdsParametrosCRT: TStringField;
    cdsParametrosEXPORTANOTASSNGPC: TStringField;
    cdsParametrosTRATANDOPREVENDASEMABERTOPAF: TStringField;
    cdsParametrosFTPENDERECO: TStringField;
    cdsParametrosFTPUSUARIO: TStringField;
    cdsParametrosFTPSENHA: TStringField;
    cdsParametrosCLIENTEORIZON: TFloatField;
    cdsParametrosCONVENIOORIZON: TFloatField;
    cdsParametrosNFECFOPDEVOLUCAOCOMPRA: TFloatField;
    cdsParametrosDIAS_CARENCIA_JUROS_CR: TIntegerField;
    cdsParametrosENQUADRAMENTOTRIBUTARIO: TStringField;
    cdsParametrosRECEBECREDITOCONTASRECEBER: TStringField;
    cdsParametrosNFEFORNECEDORDEVOLUCAOVENDA: TFloatField;
    cdsParametrosCLIENTEPHARMASYSTEM: TFloatField;
    cdsParametrosCONVENIOPHARMASYSTEM: TFloatField;
    cdsParametrosSENHAPHARMASYSTEM: TStringField;
    cdsParametrosCONCESSAOCREDITOS: TStringField;
    cdsParametrosNFETIPOEMISSAO: TStringField;
    cdsParametrosSERIENOTANFESCAN: TStringField;
    cdsParametrosNFEULTIMANOTAEMITIDASCAN: TStringField;
    cdsParametrosVERSAONFE: TIntegerField;
    cdsParametrosUSACONFERENCIABALCAO: TStringField;
    cdsParametrosNFCEAMBIENTE: TStringField;
    cdsParametrosNFCENOTA: TStringField;
    cdsParametrosNFCELOTE: TStringField;
    cdsParametrosNFCESERIE: TStringField;
    cdsParametrosNFCECIDTOKEN: TStringField;
    cdsParametrosNFCETOKEN: TStringField;
    cdsParametrosNFEPERCENTUALCREDITOSN: TFloatField;
    cdsParametrosPORTA_SMTP: TStringField;
    cdsParametrosPHARMALINKDIRETORIOENVIO: TStringField;
    cdsParametrosPHARMALINKDIRETORIORETORNO: TStringField;
    cdsParametrosPISALIQUOTA: TFMTBCDField;
    cdsParametrosCOFINSALIQUOTA: TFMTBCDField;
    cdsParametrosAVISOPREVENDAABERTA: TStringField;
    cdsParametrosTEMPOAVISOPREVENDAABERTA: TIntegerField;
    cdsParametrosFIDELIZEFTPHOST: TStringField;
    cdsParametrosFIDELIZEFTPUSUARIO: TStringField;
    cdsParametrosFIDELIZEFTPSENHA: TStringField;
    cdsParametrosUSACONSULTAPRODUTOSPBM: TStringField;
    cdsParametrosWSCONVENIOURL: TStringField;
    cdsParametrosWSCONVENIOCODIGOACESSO: TStringField;
    cdsParametrosWSCONVENIOSENHA: TStringField;
    cdsParametrosWSCONVENIOOPERADOR: TStringField;
    cdsParametrosWSCONVENIOTOKEN: TStringField;
    cdsParametrosEXIBEIMAGEMPRODUTO: TStringField;
    cdsParametrosCLIENTEWSCONVENIO: TFloatField;
    cdsParametrosCONVENIOWSCONVENIO: TFloatField;
    cdsParametrosTEFCNPJCREDENCIADORA: TStringField;
    cdsParametrosPREVENDASBLOQUEIAVENDEDOR: TIntegerField;
    cdsParametrosAVANT_IDINTEGRACAO: TStringField;
    cdsParametrosAVANT_IDEMPRESA: TStringField;
    cdsParametrosAVANT_TOKEN: TStringField;
    cdsParametrosAVANT_DATAREVISAO: TDateField;
    cdsParametrosAVANT_DATAATUALIZACAO: TDateField;
    cdsParametrosSANGRIABLOQUEIACHECKOUT: TStringField;
    cdsParametrosWSCONVENIOURLCADASTRO: TStringField;
    cdsParametrosDESCONTOCONVENIOSOBREFIDELIDADE: TStringField;
    cdsParametrosABCFARMA_SENHA: TStringField;
    cdsParametrosSMTPSSL: TStringField;
    cdsParametrosSMTPTLS: TStringField;
    cdsParametrosEXPORTAPRODUTOSFISCO: TStringField;
    cdsParametrosNFCEIDENTIFICARSH: TStringField;
    cdsParametrosNFCEIDENTIFICARTEF: TStringField;
    cdsParametrosNFCEIDENTIFICARST: TStringField;
    cdsParametrosNFCEIDENTIFICACSRT: TStringField;
    cdsParametrosNFCEIDCSRT: TIntegerField;
    cdsParametrosNFCEHASHCSRT: TStringField;
    cdsParametrosNFCEIDENTIFICARICMSEFETIVO: TStringField;
    cdsParametrosPROGRAMAFISCAL: TIntegerField;
    cdsParametrosNFCEGERAICMSDESONERACAO: TStringField;
    cdsParametrosALTERARQUANTIDADERECEBIDA: TStringField;
    cdsParametrosORIZONXAPIKEY: TStringField;
    cdsParametrosMENSAGEMSANGRIADINHEIRO: TStringField;
    cdsParametrosSAT_SERIE: TIntegerField;
    cdsParametrosINDICACONVENIOCADASTROVENDA: TStringField;
    cdsParametrosDATAHORAEXECUTAVEL: TSQLTimeStampField;
    cdsParametrosCERTIFICADODIGITAL: TBlobField;
    cdsParametrosSENHACERTIFICADODIGITAL: TStringField;
    cdsParametrosID_PRODUTO_SERVICO: TFloatField;
    cdsParametrosID_PRODUTO_ENTREGA: TFloatField;
    cdsParametrosMONITORNFES: TStringField;
    cdsParametrosCONFERENCIAVENDADIRETACHECKOUT: TStringField;
    cdsParametrosORIZON_LOGIN: TStringField;
    cdsParametrosORIZON_SENHA: TStringField;
    cdsParametrosSOLICITAAUTORIZACAOCARTAO: TStringField;
    cdsParametrosUSACONSULTAPRODUTOSPBMPDV: TStringField;
    cdsParametrosUSACONFERENCIATRANSFERENCIA: TStringField;
    cdsParametrosIMPRIMECUPOMEXCLUSAOITEM: TStringField;
    FDControlador: TFDQuery;
    dspControlador: TDataSetProvider;
    cdsControlador: TClientDataSet;
    cdsControladorN_ITENS: TIntegerField;
    cdsControladorN_UNIDADES: TFloatField;
    cdsControladorT_CUSTO: TFloatField;
    cdsControladorT_VENDA: TFloatField;
    cdsControladorT_PROMOCAO: TFloatField;
    cdsControladorCLASSES: TFloatField;
    cdsControladorGRUPOS: TFloatField;
    cdsControladorLABORATORIOS: TFloatField;
    cdsControladorDISTRIBUIDORES: TFloatField;
    cdsControladorFAMILIAS: TFloatField;
    cdsControladorGRUPOSBALANCO: TFloatField;
    cdsControladorGRUPOSCOMPRAS: TFloatField;
    cdsControladorCARTOES: TFloatField;
    cdsControladorLANCAMENTOS: TFloatField;
    cdsControladorCAIXAS: TFloatField;
    cdsControladorCONTASRECEBER: TFloatField;
    FDSql1: TFDQuery;
    dspSql1: TDataSetProvider;
    cdsSql1: TClientDataSet;
    IntegerField1: TIntegerField;
    FloatField1: TFloatField;
    FloatField2: TFloatField;
    FloatField3: TFloatField;
    FloatField4: TFloatField;
    FloatField5: TFloatField;
    FloatField6: TFloatField;
    FloatField7: TFloatField;
    FloatField8: TFloatField;
    FloatField9: TFloatField;
    FloatField10: TFloatField;
    FloatField11: TFloatField;
    FloatField12: TFloatField;
    FloatField13: TFloatField;
    FloatField14: TFloatField;
    FloatField15: TFloatField;
    FDceLotes2: TFDQuery;
    dspCelotes2: TDataSetProvider;
    cdsCelotes2: TClientDataSet;
    cdsCelotes2ID_PRODUTO: TFloatField;
    cdsCelotes2CD_FILIAL: TFloatField;
    cdsCelotes2CD_PRODUTO: TStringField;
    cdsCelotes2DESCRICAO: TStringField;
    cdsCelotes2CD_LABORATORIO: TFloatField;
    cdsCelotes2CD_GRUPO: TFloatField;
    cdsCelotes2CD_CONVENIO: TFloatField;
    cdsCelotes2CD_CLIENTE: TFloatField;
    cdsCelotes2CD_VENDEDOR: TFloatField;
    cdsCelotes2CD_OPERADOR: TFloatField;
    cdsCelotes2CD_USUARIO: TFloatField;
    cdsCelotes2CD_FORMA_PAGAMENTO: TFloatField;
    cdsCelotes2CD_VENDA: TFloatField;
    cdsCelotes2CUSTO_MEDIO: TFMTBCDField;
    cdsCelotes2CUSTO_UNITARIO: TFMTBCDField;
    cdsCelotes2DATA_LANCAMENTO: TDateField;
    cdsCelotes2DATA_CAIXA: TDateField;
    cdsCelotes2QUANTIDADE: TFloatField;
    cdsCelotes2VALOR: TFMTBCDField;
    cdsCelotes2NOTA_FISCAL: TStringField;
    cdsCelotes2DESCONTO: TFMTBCDField;
    cdsCelotes2PROMOCAO: TFMTBCDField;
    cdsCelotes2TIPO_VENDA: TStringField;
    cdsCelotes2TIPO_PAGAMENTO: TStringField;
    cdsCelotes2ENTRADA_SAIDA: TStringField;
    cdsCelotes2ETIQUETA: TStringField;
    cdsCelotes2ENTREGA: TStringField;
    cdsCelotes2HORA: TTimeField;
    cdsCelotes2ESTOQUE_POSVENDA: TFloatField;
    cdsCelotes2TROCA: TStringField;
    cdsCelotes2ENVIADO: TStringField;
    cdsCelotes2NUMERO: TFloatField;
    cdsCelotes2TERMINAL: TFloatField;
    cdsCelotes2USUARIO: TStringField;
    cdsCelotes2CD_LANCAMENTO: TFloatField;
    cdsCelotes2COMISSAO: TFMTBCDField;
    cdsCelotes2ARREDONDAMENTO: TFMTBCDField;
    cdsCelotes2CD_CLASSE: TFloatField;
    cdsCelotes2ID_OPERADORCAIXA: TFloatField;
    cdsCelotes2OBSERVACAO: TStringField;
    cdsCelotes2TRN: TStringField;
    cdsCelotes2TRANSACAOTRN: TStringField;
    cdsCelotes2LOTETRN: TStringField;
    cdsCelotes2AUTORIZACAOTRN: TStringField;
    cdsCelotes2SUBSIDIOTRN: TFloatField;
    cdsCelotes2NOTAMANUAL: TStringField;
    FDNumeroCaixaLoja: TFDQuery;
    dspNUmeroCaixaLoja: TDataSetProvider;
    cdsNumeroCaixaLoja: TClientDataSet;
    cdsNumeroCaixaLojaCOUNT: TIntegerField;
    FDCaixaLoja: TFDQuery;
    dspCaixaLoja: TDataSetProvider;
    cdsCaixaLoja: TClientDataSet;
    cdsCaixaLojaCD_CAIXA: TFloatField;
    CdsCdCaixa: TClientDataSet;
    CdsCdCaixaCD_CAIXA: TFloatField;
    FDCeCaixa: TFDQuery;
    dspCeCaixa: TDataSetProvider;
    cdsCeCaixa: TClientDataSet;
    cdsCeCaixaCD_CAIXA: TFloatField;
    cdsCeCaixaCD_FILIAL: TFloatField;
    cdsCeCaixaCD_CONVENIO: TFloatField;
    cdsCeCaixaCD_CLIENTE: TFloatField;
    cdsCeCaixaCD_VENDEDOR: TFloatField;
    cdsCeCaixaCD_OPERADOR: TFloatField;
    cdsCeCaixaCD_USUARIO: TFloatField;
    cdsCeCaixaCD_FORMA_PAGAMENTO: TFloatField;
    cdsCeCaixaCD_PLANO_CONTAS: TFloatField;
    cdsCeCaixaCD_CARTAO: TFloatField;
    cdsCeCaixaCD_VENDA: TFloatField;
    cdsCeCaixaID_OPERADORCAIXA: TFloatField;
    cdsCeCaixaTIPO_CARTAO: TStringField;
    cdsCeCaixaDATA: TDateField;
    cdsCeCaixaHORA: TTimeField;
    cdsCeCaixaVALOR: TFloatField;
    cdsCeCaixaDOCUMENTO: TStringField;
    cdsCeCaixaDESCONTO: TFloatField;
    cdsCeCaixaTIPO_VENDA: TStringField;
    cdsCeCaixaENTRADA_SAIDA: TStringField;
    cdsCeCaixaENTREGA: TStringField;
    cdsCeCaixaTROCA: TStringField;
    cdsCeCaixaENVIADO: TStringField;
    cdsCeCaixaUSUARIO: TStringField;
    cdsCeCaixaNUMERO: TFloatField;
    cdsCeCaixaDATA_VENCIMENTO: TDateField;
    cdsCeCaixaTERMINAL: TFloatField;
    cdsCeCaixaNR_CHEQUE: TStringField;
    cdsCeCaixaNR_BANCO: TStringField;
    cdsCeCaixaDATA_CAIXA: TDateField;
    cdsCeCaixaOBSERVACAO: TStringField;
    cdsCeCaixaARREDONDAMENTO: TFloatField;
    cdsCeCaixaTEFTRANSACAO: TFloatField;
    cdsCeCaixaTEFLOTE: TFloatField;
    cdsCeCaixaTEFAUTORIZACAO: TStringField;
    cdsCeCaixaTEFDATA: TDateField;
    cdsCeCaixaTEFHORA: TTimeField;
    cdsCeCaixaTEFVALOR: TFloatField;
    cdsCeCaixaTEFNOMEREDE: TStringField;
    cdsCeCaixaSTATUS: TStringField;
    cdsCeCaixaTRN: TStringField;
    cdsCeCaixaTRANSACAOTRN: TStringField;
    cdsCeCaixaLOTETRN: TStringField;
    cdsCeCaixaAUTORIZACAOTRN: TStringField;
    cdsCeCaixaPARCELA: TIntegerField;
    cdsCeCaixaCD_FILIAL_ORIGEM: TFloatField;
    cdsCeCaixaECF: TStringField;
    CdsIncluiProdutos: TClientDataSet;
    CdsIncluiProdutosID_PRODUTO: TFloatField;
    CdsIncluiProdutosCD_PRODUTO: TStringField;
    CdsIncluiProdutosCODIGO_BARRAS_1: TStringField;
    CdsIncluiProdutosCODIGO_BARRAS_2: TStringField;
    CdsIncluiProdutosDESCRICAO: TStringField;
    CdsIncluiProdutosCD_LABORATORIO: TFloatField;
    CdsIncluiProdutosCD_GRUPO: TFloatField;
    CdsIncluiProdutosCD_GRUPOBALANCO: TFloatField;
    CdsIncluiProdutosCD_GRUPOCOMPRA: TFloatField;
    CdsIncluiProdutosCD_CLASSE: TFloatField;
    CdsIncluiProdutosID_FAMILIA: TFloatField;
    CdsIncluiProdutosTIPO_PRODUTO: TStringField;
    CdsIncluiProdutosENTRA_PEDIDO_ELETRONICO: TStringField;
    CdsIncluiProdutosCD_LISTA: TFloatField;
    CdsIncluiProdutosTX_DESCONTO: TFloatField;
    CdsIncluiProdutosIDENTIFICADOR: TStringField;
    CdsIncluiProdutosBALANCA: TStringField;
    CdsIncluiProdutosUNIDADE: TStringField;
    CdsIncluiProdutosQT_EMBALAGEM: TFloatField;
    CdsIncluiProdutosCOMISSAO: TFloatField;
    CdsIncluiProdutosPRECO_VENDA: TFloatField;
    CdsIncluiProdutosPRECO_PROMOCAO: TFloatField;
    CdsIncluiProdutosICMS: TStringField;
    CdsIncluiProdutosMARGEM: TFloatField;
    CdsIncluiProdutosMARGEM_PROMOCAO: TFloatField;
    CdsIncluiProdutosDT_CADASTRO: TDateField;
    CdsIncluiProdutosCURVA: TStringField;
    CdsIncluiProdutosSTATUS: TStringField;
    CdsIncluiProdutosUSOCONTINUO: TStringField;
    CdsIncluiProdutosPIS_COFINS: TStringField;
    CdsIncluiProdutosNCM: TStringField;
    CdsIncluiProdutosCD_SUBGRUPO: TFloatField;
    CdsIncluiProdutosCEST: TStringField;
    CdsIncluiProdutosCD_CFOP: TFloatField;
    CdsIncluiProdutosSITUACAOTRIBUTARIA: TStringField;
    CdsIncluiProdutosORIGEM: TStringField;
    CdsIncluiProdutosCSOSN: TStringField;
    CdsIncluiProdutosIAT: TStringField;
    CdsIncluiProdutosIPPT: TStringField;
    CdsIncluiProdutosCOMPRIMIDOSCAIXA: TFloatField;
    CdsIncluiProdutosCONTROLADO: TStringField;
    CdsIncluiProdutosGENERICO: TStringField;
    CdsIncluiProdutosCD_PRINCIPIO: TFloatField;
    CdsIncluiProdutosDT_VENCIMENTO_PROMOCAO: TDateField;
    CdsIncluiProdutosCUSTO_UNITARIO: TFloatField;
    CdsIncluiProdutosOBSERVACAO: TStringField;
    DspCeProdutos: TDataSetProvider;
    CdsCeProdutos: TClientDataSet;
    FDCeProdutos: TFDQuery;
    dspOperadores: TDataSetProvider;
    cdsOperadores: TClientDataSet;
    FDOperadores: TFDQuery;
    cdsOperadoresID_OPERADORCAIXA: TFloatField;
    cdsOperadoresCD_FILIAL: TFloatField;
    cdsOperadoresCD_OPERADOR: TFloatField;
    cdsOperadoresCD_USUARIO: TFloatField;
    cdsOperadoresNOME: TStringField;
    cdsOperadoresTERMINAL: TFloatField;
    cdsOperadoresDATA_ABERTURA: TDateField;
    cdsOperadoresDATA_FECHAMENTO: TDateField;
    cdsOperadoresHORA_ABERTURA: TTimeField;
    cdsOperadoresHORA_FECHAMENTO: TTimeField;
    cdsOperadoresDINHEIRO: TFloatField;
    cdsOperadoresCHEQUE_PRE: TFloatField;
    cdsOperadoresCHEQUE_A_VISTA: TFloatField;
    cdsOperadoresCARTAO: TFloatField;
    cdsOperadoresCONVENIO: TFloatField;
    cdsOperadoresCREDITO: TFloatField;
    cdsOperadoresSAIDAS: TFloatField;
    cdsOperadoresENVIADO: TStringField;
    cdsOperadoresSTATUS: TStringField;
    dspCrm: TDataSetProvider;
    cdsCRM: TClientDataSet;
    FDCrm: TFDQuery;
    cdsCRMID_CRM: TFloatField;
    cdsCRMCD_FILIAL: TFloatField;
    cdsCRMCNPJ: TStringField;
    cdsCRMCRM: TStringField;
    cdsCRMUF: TStringField;
    cdsCRMCD_VENDA: TFloatField;
    cdsCRMCD_VENDEDOR: TFloatField;
    cdsCRMMEDICO: TStringField;
    cdsCRMCODIGO_BARRA: TStringField;
    cdsCRMDESCRICAO: TStringField;
    cdsCRMQUANTIDADE: TFloatField;
    cdsCRMDATA: TDateField;
    cdsCRMHORA: TTimeField;
    cdsCRMID_MEDICO: TFloatField;
    cdsCRMID_ENDERECO: TFloatField;
    cdsCRMID_AREA: TFloatField;
    cdsCRMTIPO: TStringField;
    cdsCRMCEP: TStringField;
    cdsCRMIMS: TStringField;
    cdsCRMID_PRODUTO: TFloatField;
    cdsCRMCD_LABORATORIO: TFloatField;
    cdsCRMFILIAL: TFloatField;
    cdsCRMTIPO_CRM: TStringField;
    cdsCRMGEN: TStringField;
    cdsCRMENVIADO: TStringField;
    dspEntregas: TDataSetProvider;
    cdsEntregas: TClientDataSet;
    FdEntregas: TFDQuery;
    cdsEntregasCD_FILIAL: TFloatField;
    cdsEntregasCD_VENDA: TFloatField;
    cdsEntregasCD_ENTREGADOR: TFloatField;
    cdsEntregasCD_CLIENTE: TFloatField;
    cdsEntregasNOME: TStringField;
    cdsEntregasENDERECO: TStringField;
    cdsEntregasBAIRRO: TStringField;
    cdsEntregasREFERENCIA: TStringField;
    cdsEntregasDATA: TDateField;
    cdsEntregasHORA_SAIDA: TTimeField;
    cdsEntregasHORA_CHEGADA: TTimeField;
    cdsEntregasTROCO: TFloatField;
    cdsEntregasVALORRETORNO: TFloatField;
    cdsEntregasENVIADO: TStringField;
    cdsEntregasSTATUS: TStringField;
    cdsEntregasOBSERVACAO: TMemoField;
    cdsEntregasHORAINICIAL: TTimeField;
    cdsEntregasHORAFINAL: TTimeField;
    procedure DataModuleCreate(Sender: TObject);
  private
    { Private declarations }
  public

      var
       BaseUrl,cdfilialparametro:string;

      procedure ValidaBd;
      function  Crypt(Action, Src: String): String;



  end;

var
  DM: TDM;

implementation

{%CLASSGROUP 'Vcl.Controls.TControl'}

uses Funcoes;

{$R *.dfm}

procedure TDM.DataModuleCreate(Sender: TObject);
begin
   ValidaBd;
   BaseUrl:='http://localhost:9000';
end;


function  TDM.Crypt(Action, Src: String): String;

var KeyLen : Integer;
  KeyPos : Integer;
  OffSet : Integer;
  Dest, Key : String;
  SrcPos : Integer;
  SrcAsc : Integer;
  TmpSrcAsc : Integer;
  Range : Integer;

begin
  if (Src = '') Then
  begin
    Result:= '';
    Exit;
  end;
  Key :=
'YUQL23KL23DF90WI5E1JAS467NMCXXL6JAOAUWWMCL0AOMM4A4VZYW9KHJUI2347EJHJKDF3424SKL K3LAKDJSL9RTIKJ';
  Dest := '';
  KeyLen := Length(Key);
  KeyPos := 0;
  SrcPos := 0;
  SrcAsc := 0;
  Range := 256;
  if (Action = UpperCase('C')) then
  begin
    Randomize;
    OffSet := Random(Range);
    Dest := Format('%1.2x',[OffSet]);
    for SrcPos := 1 to Length(Src) do
    begin
      Application.ProcessMessages;
      SrcAsc := (Ord(Src[SrcPos]) + OffSet) Mod 255;
      if KeyPos < KeyLen then KeyPos := KeyPos + 1 else KeyPos := 1;
      SrcAsc := SrcAsc Xor Ord(Key[KeyPos]);
      Dest := Dest + Format('%1.2x',[SrcAsc]);
      OffSet := SrcAsc;
    end;
  end
  Else if (Action = UpperCase('D')) then
  begin
    OffSet := StrToIntDef('$'+ copy(Src,1,2),0);
    SrcPos := 3;
  repeat
    SrcAsc := StrToIntDef('$'+ copy(Src,SrcPos,2),0);
    if (KeyPos < KeyLen) Then KeyPos := KeyPos + 1 else KeyPos := 1;
    TmpSrcAsc := SrcAsc Xor Ord(Key[KeyPos]);
    if TmpSrcAsc <= OffSet then TmpSrcAsc := 255 + TmpSrcAsc - OffSet
    else TmpSrcAsc := TmpSrcAsc - OffSet;
    Dest := Dest + Chr(TmpSrcAsc);
    OffSet := SrcAsc;
    SrcPos := SrcPos + 2;
  until (SrcPos >= Length(Src));
  end;
  Result:= Dest;


end;

procedure TDM.ValidaBd;

var
 CaminhoBD,NOmeServidor : String;
 ini:TInifile;
begin


    if not FileExists(extractFilePath(ParamStr(0))+'CaminhoBD.ini') then
    begin
      showmessage(' Instalar na Pasta do Farmax'+#13+ 'para pegar as configurações do servidor.');
                 exit;
    end;

    ini := TiniFile.Create(ExtractFilePath(Application.ExeName)+'CaminhoBD.ini');
    CaminhoBD    := Crypt('D', ini.ReadString('CAMINHO','CAMINHO','Caminho'));
    NomeServidor := Crypt('D', ini.ReadString('NOME','NOME','NomedoServidorDB'));
    ini.Free;

     begin

       try
         dm.FDConn.Connected:=false;
         dm.Fdconn.Close;
         dm.Fdconn.Params.Values['DriverID']  :='FB';
         dm.Fdconn.Params.Values['Server']    := NomeServidor;
         dm.Fdconn.Params.Values['Database']  := CaminhoBD;
         dm.Fdconn.Params.Values['User_Name'] :='sysdba';
         dm.Fdconn.Params.Values['Password']  :='masterkey';
         dm.Fdconn.Params.Values['Port']      :='3050';
         dm.Fdconn.Params.Values['Protocol']  :='TCPIP';
         dm.Fdconn.Connected;
         dm.Fdconn.Connected:=true;

       except on E: Exception do

         GeraLog('Erro ao conectar no servidor :'+E.Message);
        end;


     end;




end;

end.
